/**
 * vite.docs.config.ts
 *
 * Builds self-contained component bundles for the Eleventy documentation site.
 * Run with: `npm run docs`  (calls `vite build --config vite.docs.config.ts`
 * as part of the full docs pipeline).
 *
 * ## Why a separate config?
 *
 * The library build (`vite.lib.config.ts`) externalizes Lit and all peer deps
 * so shipped bundles stay tiny.  That is ideal for npm consumers, but the docs
 * site is a static HTML site — it has no package manager and cannot resolve
 * bare specifiers like `import 'lit'` at runtime.
 *
 * This config produces "bundled" variants where Lit is fully inlined, so each
 * output file is a standalone module that a `<script type="module">` tag can
 * load directly from a CDN or static host with zero additional setup.
 *
 * ## Output structure
 *
 * Files land inside the existing `docs/` directory alongside Eleventy's HTML:
 *
 *   docs/
 *   ├── index.html                ← generated by Eleventy
 *   ├── mu-avatar.bundled.js      ← self-contained bundle (Lit inlined)
 *   ├── mu-button.bundled.js
 *   ├── mu-card.bundled.js
 *   └── mu-icon.bundled.js
 *
 * ## Adding a component to the docs
 *
 * 1. Add a new entry below using the `<tag-name>.bundled` naming convention.
 * 2. Reference the output file in the relevant Eleventy template:
 *    `<script type="module" src="/mu-button.bundled.js"></script>`
 *
 * ## Note on bundle size
 *
 * Because Lit is included in every bundle, each file is larger than the
 * equivalent library entry (~25 kB vs ~3 kB for `mu-button`).  This is
 * acceptable for a documentation site where HTTP/2 multiplexing and
 * browser caching mitigate the overhead.  Do not use these bundles in
 * production application code — use the library entries instead.
 */
import {resolve} from 'node:path';
import {defineConfig} from 'vite';

export default defineConfig({
  build: {
    /** Eleventy writes its HTML output here; we append our JS bundles alongside it. */
    outDir: 'docs',
    /**
     * Do NOT wipe the directory before building.  Eleventy generates HTML
     * separately (via `npm run docs:gen`) and clearing `docs/` here would
     * delete those files.  The `docs:clean` script handles full resets.
     */
    emptyOutDir: false,
    /**
     * Source maps are omitted for the public docs site to reduce payload size.
     * Enable temporarily during docs debugging by setting this to `true`.
     */
    sourcemap: false,
    /**
     * Match the library target so the bundled files can run in the same
     * browsers that the library itself supports.
     */
    target: 'es2021',
    lib: {
      /**
       * Each entry produces one fully self-contained ES module.  The
       * `.bundled` suffix in the key distinguishes these artefacts from the
       * tree-shakeable library entries and signals to readers that Lit is
       * inlined rather than externalised.
       *
       * Only components that appear in live documentation examples need to be
       * listed here.  You do NOT need an entry for every component in the
       * library — the docs site only loads what it actually renders.
       */
      entry: {
        'mu-avatar.bundled': resolve(__dirname, 'src/core/components/avatar/mu-avatar.ts'),
        'mu-button.bundled': resolve(__dirname, 'src/core/components/button/mu-button.ts'),
        'mu-card.bundled': resolve(__dirname, 'src/core/components/card/mu-card.ts'),
        'mu-icon.bundled': resolve(__dirname, 'src/core/components/icon/mu-icon.ts'),
      },
      /**
       * ES module output only — the docs site uses `<script type="module">`
       * which requires ES module syntax.
       */
      formats: ['es'],
    },
    rollupOptions: {
      /**
       * No `external` list here.  Unlike the library build, all imports
       * (including Lit) are resolved and bundled so pages work without any
       * import-map or CDN setup.
       */
      output: {
        /**
         * Preserve the `[name].js` pattern so Eleventy templates can
         * reference predictable file names such as `mu-button.bundled.js`.
         */
        entryFileNames: '[name].js',
      },
    },
  },
});
